// Portfolio data - centralized for easy updates
export const DATA = {
  name: 'Lin Phone Myint Zaw',
  title: 'Full‑Stack / React Native Developer',
  location: 'Yangon, Myanmar',
  phone: '+95 996 765 8131',
  email: 'linphonem@gmail.com',
  links: {
    linkedin: 'https://www.linkedin.com/in/lin-phone-myint-zaw-025082176/',
    github: 'https://github.com/linphone2000',
  },
  summary:
    'Junior Software Engineer experienced in React Native, MERN, and backend (Node.js, Express). Passionate about building real products that solve problems, clean architecture, and AI.',
  // Add more detailed personal info
  about: {
    tagline:
      'Building mobile-first experiences with strong API and data modeling foundations',
    availability: 'Available for freelance opportunities',
    yearsOfExperience: 2,
    totalProjects: 5,
    technologiesMastered: 12,
    typewriterStrings: [
      'Full‑Stack / React Native Developer',
      'Graduate from Edinburgh Napier University',
      'Building real products with clean code',
    ],
  },
  experience: [
    {
      company: 'HighGround',
      role: 'Junior Developer (Remote)',
      period: 'July 2025 – Present',
      location: 'Remote',
      type: 'Full-time',
      bullets: [
        'Developing cross‑platform mobile apps with React Native in an Agile environment.',
        'Work on overseas projects with international clients.',
      ],
      technologies: ['React Native', 'TypeScript', 'Agile', 'Documentation'],
    },
    {
      company: 'NTT Data Myanmar',
      role: 'Junior System Engineer (Application Dev)',
      period: 'April 2025 – June 2025',
      location: 'Yangon, Myanmar',
      type: 'Full-time',
      bullets: [
        'Contributed to a FinTech project, focused on backend.',
        'Hands‑on requirement gathering and documentation within a large organization.',
      ],
      technologies: [
        'Backend Development',
        'Requirements Gathering',
        'Documentation',
      ],
    },
  ],
  projects: [
    {
      name: 'PropertyApp – Advanced Trading & Investment Dashboard',
      stack: ['React Native', 'Expo', 'TypeScript', 'Zustand', 'AsyncStorage'],
      blurb:
        'Sophisticated property investment platform with real-time trading, live P&L tracking, 7-day performance charts, buy/sell functionality, and advanced portfolio analytics. Features market simulation, transaction history, and professional-grade trading interfaces.',
      href: '#',
      highlight: true,
      category: 'Mobile Development',
      year: 2025,
      status: 'Completed',
      features: [
        'Real-time Trading',
        'P&L Tracking',
        'Portfolio Analytics',
        'Market Simulation',
        '7-Day Performance Chart',
        'Virtual Trading',
      ],
      // PropertyApp-specific data for preview
      preview: {
        platform: 'iOS & Android',
        buysell: 'Buy/Sell',
        featurePills: ['Real-time Trading', 'Portfolio Analytics'],
        screenshot: '/property-project/home1.png',
        screenshots: [
          {
            id: 1,
            src: '/property-project/home1.png',
            title: 'Dashboard Overview',
            description:
              'Main trading dashboard with portfolio summary and key metrics',
          },
          {
            id: 2,
            src: '/property-project/home2.png',
            title: 'Top P&L Properties',
            description: 'Detailed portfolio performance and analytics view',
          },
          {
            id: 3,
            src: '/property-project/home3.png',
            title: 'P&L Tracking',
            description: 'Live trading interface with buy/sell functionality',
          },
          {
            id: 4,
            src: '/property-project/home4.png',
            title: 'Recent Trades',
            description: 'Profit and loss tracking with detailed analytics',
          },
          {
            id: 5,
            src: '/property-project/home5.png',
            title: 'Buy',
            description: 'Real-time market data and price charts',
          },
          {
            id: 6,
            src: '/property-project/home6.png',
            title: 'Sell',
            description: 'Complete transaction log and history view',
          },
          {
            id: 7,
            src: '/property-project/home7.png',
            title: 'Transaction Success',
            description: 'Advanced portfolio analytics and insights',
          },
          {
            id: 8,
            src: '/property-project/property1.png',
            title: 'Property Management',
            description: 'Property listing and management interface',
          },
          {
            id: 9,
            src: '/property-project/property2.png',
            title: 'Property Details',
            description: 'Detailed property information and metrics',
          },
          {
            id: 10,
            src: '/property-project/profile1.png',
            title: 'User Profile',
            description: 'User profile and account management',
          },
          {
            id: 11,
            src: '/property-project/profile2.png',
            title: 'Account Settings',
            description: 'Account settings and preferences',
          },
          {
            id: 12,
            src: '/property-project/manage1.PNG',
            title: 'Management Dashboard',
            description: 'Administrative dashboard and controls',
          },
        ],
      },
    },
    {
      name: 'Intelligent Home Surveillance System',
      stack: ['Next.js', 'TensorFlow.js', 'FaceAPI.js', 'ml5.js'],
      blurb:
        'Web‑based AI security with object detection & face recognition; switches modes based on detected classes and emails alerts for strangers.',
      href: '#',
      category: 'AI & Computer Vision',
      year: 2024,
      status: 'Completed',
      features: [
        'Object Detection',
        'Face Recognition',
        'Email Alerts',
        'Mode Switching',
      ],
      preview: {
        platform: 'Web Application',
        featurePills: ['AI-Powered Security', 'Real-time Detection'],
        screenshot: '/home-security-project/hs1.png',
        screenshots: [
          {
            id: 1,
            src: '/home-security-project/hs1.png',
            title: 'Main Dashboard',
            description: 'Central control panel for home surveillance system',
          },
          {
            id: 2,
            src: '/home-security-project/hs2.png',
            title: 'Live Monitoring',
            description: 'Real-time video feed with AI object detection',
          },
          {
            id: 3,
            src: '/home-security-project/hs3.png',
            title: 'Face Recognition',
            description: 'Face detection and recognition interface',
          },
          {
            id: 4,
            src: '/home-security-project/hs4.png',
            title: 'Alert System',
            description: 'Email alert configuration and notifications',
          },
          {
            id: 5,
            src: '/home-security-project/hs5.png',
            title: 'Object Detection',
            description: 'Real-time object classification and tracking',
          },
          {
            id: 6,
            src: '/home-security-project/hs6.png',
            title: 'Security Modes',
            description: 'Different security mode configurations',
          },
          {
            id: 7,
            src: '/home-security-project/hs7.png',
            title: 'Detection History',
            description: 'Historical logs of detected events',
          },
          {
            id: 8,
            src: '/home-security-project/hs8.png',
            title: 'Camera Settings',
            description: 'Camera configuration and calibration',
          },
          {
            id: 9,
            src: '/home-security-project/hs9.png',
            title: 'AI Model Status',
            description: 'Machine learning model performance metrics',
          },
          {
            id: 10,
            src: '/home-security-project/hs10.png',
            title: 'User Management',
            description: 'Access control and user permissions',
          },
          {
            id: 11,
            src: '/home-security-project/hs11.png',
            title: 'Analytics Dashboard',
            description: 'Security analytics and insights',
          },
          {
            id: 12,
            src: '/home-security-project/hs12.png',
            title: 'Notification Center',
            description: 'Alert history and notification management',
          },
          {
            id: 13,
            src: '/home-security-project/hs13.png',
            title: 'Settings Panel',
            description: 'System configuration and preferences',
          },
          {
            id: 14,
            src: '/home-security-project/hs14.png',
            title: 'Video Playback',
            description: 'Recorded footage review and playback',
          },
          {
            id: 15,
            src: '/home-security-project/hs15.png',
            title: 'Advanced Settings',
            description: 'Advanced AI and detection configurations',
          },
          {
            id: 16,
            src: '/home-security-project/hs16.png',
            title: 'System Overview',
            description: 'Comprehensive system status and health',
          },
        ],
      },
    },
    {
      name: 'Pharmacy Management System',
      stack: ['MERN', 'Agile', 'Team Lead'],
      blurb:
        'Inventory management web app for real‑time stock & sales; weekly client reviews; Gantt/Trello/GitHub for delivery.',
      href: '#',
      category: 'Full-Stack Development',
      year: 2024,
      status: 'Completed',
      features: [
        'Inventory Management',
        'Real-time Stock',
        'Client Reviews',
        'Team Collaboration',
      ],
      preview: {
        platform: 'Web Application',
        featurePills: ['Inventory Management', 'Real-time Tracking'],
        screenshot: '/pharmacy-management-system-project/pms1.png',
        screenshots: [
          {
            id: 1,
            src: '/pharmacy-management-system-project/pms0.png',
            title: 'Login Page',
            description: 'Secure authentication for pharmacy staff',
          },
          {
            id: 2,
            src: '/pharmacy-management-system-project/pms1.png',
            title: 'Dashboard Overview',
            description: 'Main dashboard with key metrics and insights',
          },
          {
            id: 3,
            src: '/pharmacy-management-system-project/pms2.png',
            title: 'Inventory Management',
            description: 'Complete inventory tracking and management',
          },
          {
            id: 4,
            src: '/pharmacy-management-system-project/pms3.png',
            title: 'Stock Control',
            description: 'Real-time stock levels and alerts',
          },
          {
            id: 5,
            src: '/pharmacy-management-system-project/pms4.png',
            title: 'Sales Dashboard',
            description: 'Sales tracking and analytics',
          },
          {
            id: 6,
            src: '/pharmacy-management-system-project/pms5.png',
            title: 'Product Management',
            description: 'Add, edit, and manage pharmacy products',
          },
          {
            id: 7,
            src: '/pharmacy-management-system-project/pms6.png',
            title: 'Order Processing',
            description: 'Customer order management and processing',
          },
          {
            id: 8,
            src: '/pharmacy-management-system-project/pms7.png',
            title: 'Reports & Analytics',
            description: 'Comprehensive business reports and insights',
          },
          {
            id: 9,
            src: '/pharmacy-management-system-project/pms8.png',
            title: 'Customer Management',
            description: 'Customer profiles and purchase history',
          },
          {
            id: 10,
            src: '/pharmacy-management-system-project/pms9.png',
            title: 'Supplier Management',
            description: 'Supplier information and order tracking',
          },
          {
            id: 11,
            src: '/pharmacy-management-system-project/pms10.png',
            title: 'Settings',
            description: 'System configuration and preferences',
          },
        ],
      },
    },
    {
      name: 'Hotel Booking Web Application',
      stack: ['Flask', 'React.js', 'Admin Dashboard'],
      blurb:
        'Responsive booking platform with room/hotel management and a simple admin portal.',
      href: '#',
      category: 'Full-Stack Development',
      year: 2023,
      status: 'Completed',
      features: [
        'Room Booking',
        'Hotel Management',
        'Admin Portal',
        'Responsive Design',
      ],
      preview: {
        platform: 'Web Application',
        featurePills: ['Hotel Booking', 'Admin Management'],
        screenshot: '/scape-booking-project/sb1.png',
        screenshots: [
          {
            id: 1,
            src: '/scape-booking-project/sb0.png',
            title: 'Landing Page',
            description: 'Welcome page with featured hotels',
          },
          {
            id: 2,
            src: '/scape-booking-project/sb1.png',
            title: 'Hotel Listings',
            description: 'Browse available hotels and rooms',
          },
          {
            id: 3,
            src: '/scape-booking-project/sb2.png',
            title: 'Hotel Details',
            description: 'Detailed hotel information and amenities',
          },
          {
            id: 4,
            src: '/scape-booking-project/sb3.png',
            title: 'Room Selection',
            description: 'Choose rooms and check availability',
          },
          {
            id: 5,
            src: '/scape-booking-project/sb4.png',
            title: 'Booking Process',
            description: 'Complete booking form and reservation',
          },
          {
            id: 6,
            src: '/scape-booking-project/sb5.png',
            title: 'Admin Dashboard',
            description: 'Administrative control panel',
          },
          {
            id: 7,
            src: '/scape-booking-project/sb6.png',
            title: 'Management Portal',
            description: 'Hotel and room management interface',
          },
        ],
      },
    },
    {
      name: 'Peer‑to‑peer Rental Platform',
      stack: ['Next.js', 'Cloudinary', 'Search & Filters'],
      blurb:
        'Scalable listings site with advanced filtering and media storage via Cloudinary.',
      href: '#',
      category: 'Web Development',
      year: 2023,
      status: 'Completed',
      features: [
        'Advanced Filtering',
        'Media Storage',
        'Scalable Architecture',
        'Cloud Integration',
      ],
      preview: {
        platform: 'Web Application',
        featurePills: ['P2P Rental', 'Cloud Storage'],
        screenshot: '/travel-scape-project/ts1.png',
        screenshots: [
          {
            id: 1,
            src: '/travel-scape-project/ts1.png',
            title: 'Home Page',
            description: 'Landing page with featured properties',
          },
          {
            id: 2,
            src: '/travel-scape-project/ts2.png',
            title: 'Property Listings',
            description: 'Browse available rental properties',
          },
          {
            id: 3,
            src: '/travel-scape-project/ts3.png',
            title: 'Advanced Search',
            description: 'Filter and search for perfect properties',
          },
          {
            id: 4,
            src: '/travel-scape-project/ts4.png',
            title: 'Property Details',
            description: 'Detailed property information and images',
          },
          {
            id: 5,
            src: '/travel-scape-project/ts5.png',
            title: 'Booking Interface',
            description: 'Date selection and booking confirmation',
          },
          {
            id: 6,
            src: '/travel-scape-project/ts6.png',
            title: 'User Profile',
            description: 'User dashboard and profile management',
          },
          {
            id: 7,
            src: '/travel-scape-project/ts7.png',
            title: 'Host Dashboard',
            description: 'Property owner management interface',
          },
          {
            id: 8,
            src: '/travel-scape-project/ts8.png',
            title: 'Listing Creation',
            description: 'Create and publish new property listings',
          },
          {
            id: 9,
            src: '/travel-scape-project/ts9.png',
            title: 'Image Upload',
            description: 'Cloudinary-powered image management',
          },
          {
            id: 10,
            src: '/travel-scape-project/ts10.png',
            title: 'Reservation Management',
            description: 'View and manage bookings',
          },
          {
            id: 11,
            src: '/travel-scape-project/ts11.png',
            title: 'Reviews & Ratings',
            description: 'Customer feedback and ratings system',
          },
          {
            id: 12,
            src: '/travel-scape-project/ts12.png',
            title: 'Payment Integration',
            description: 'Secure payment processing interface',
          },
          {
            id: 13,
            src: '/travel-scape-project/ts13.png',
            title: 'Settings',
            description: 'Account settings and preferences',
          },
        ],
      },
    },
  ],
  skills: {
    frontend: ['React Native', 'React.js', 'Next.js', 'WordPress'],
    backend: ['Node.js', 'Express.js', 'Flask'],
    databases: ['MongoDB', 'MySQL'],
    languages: ['TypeScript', 'JavaScript', 'Python', 'Java'],
    tools: [
      'Expo',
      'Git',
      'GitHub',
      'Bitbucket',
      'Postman',
      'Docker',
      'Trello',
      'Gantt Charts',
    ],
    aiml: ['TensorFlow.js', 'OpenCV', 'CNN Models', 'COCO‑SSD'],
    soft: ['Communication', 'Collaboration', 'Presentation', 'Adaptability'],
    // Add skill proficiency levels
    proficiency: {
      expert: ['React Native', 'TypeScript', 'JavaScript'],
      advanced: ['React.js', 'Node.js', 'Express.js', 'MongoDB'],
      intermediate: ['Next.js', 'Python', 'MySQL', 'TensorFlow.js'],
      beginner: ['Java', 'Docker', 'OpenCV'],
    },
  },
  education: [
    {
      school: 'Edinburgh Napier University',
      credential: 'BSc (Hons) in Computing – Distinction',
      period: 'Aug 2023 – Mar 2025',
      location: 'Edinburgh, UK',
      gpa: 'Distinction',
      relevantCourses: [
        'Software Engineering',
        'Database Systems',
        'Web Development',
        'AI & Machine Learning',
      ],
    },
    {
      school: 'Info Myanmar College',
      credential: 'Higher National Diploma in Software Engineering – Merits',
      period: 'Apr 2022 – Jun 2023',
      location: 'Yangon, Myanmar',
      gpa: 'Merits',
      relevantCourses: [
        'Programming Fundamentals',
        'Software Design',
        'Database Management',
        'System Analysis',
      ],
    },
  ],
  certs: [
    {
      name: 'IT Passport (ITPEC)',
      year: 2022,
      issuer: 'ITPEC',
      description: 'Information Technology Passport Examination',
    },
    {
      name: 'Basic Linux Skills',
      year: 2019,
      issuer: 'Linux Foundation',
      description: 'Fundamental Linux system administration',
    },
    {
      name: 'Network Engineering',
      year: 2018,
      issuer: 'Cisco',
      description: 'Network infrastructure and protocols',
    },
    {
      name: 'Intermediate English',
      year: 2018,
      issuer: 'Cambridge English',
      description: 'B2 level English proficiency',
    },
    {
      name: 'CompTIA A+',
      year: 2016,
      issuer: 'CompTIA',
      description: 'IT fundamentals and hardware support',
    },
  ],
  // Add achievements and milestones
  achievements: [
    {
      title: 'Remote Developer Success',
      description:
        'Successfully working as a remote React Native developer at HighGround',
      year: 2025,
      category: 'Professional',
    },
    {
      title: 'FinTech Project Contribution',
      description: 'Contributed to a FinTech project at NTT Data Myanmar',
      year: 2025,
      category: 'Professional',
    },
    {
      title: 'Distinction Graduate',
      description:
        'Achieved 1ˢᵗ Class Honours in BSc Computing from Edinburgh Napier University',
      year: 2025,
      category: 'Academic',
    },
  ],
  // Add services offered
  services: [
    {
      title: 'Mobile Development',
      description:
        'Cross-platform React Native apps with clean architecture and excellent UX',
      technologies: ['React Native', 'Expo'],
      icon: 'mobile',
    },
    {
      title: 'Full-Stack Solutions',
      description:
        'Complete MERN stack applications with robust backend APIs and databases',
      technologies: ['MERN', 'Node.js'],
      icon: 'fullstack',
    },
    {
      title: 'Clean Architecture',
      description:
        'Well-documented, maintainable code with strong development practices',
      technologies: ['TypeScript', 'Clean Code'],
      icon: 'architecture',
    },
  ],
};
