export type ProductType = 'web' | 'mobile';

export type FeatureCategory =
  | 'essential'
  | 'commerce'
  | 'education'
  | 'platform';

export type FeatureDefinition = {
  id: string;
  name: string;
  nameMm?: string;
  desc?: string;
  baseCost: number;
  category: FeatureCategory;
  tags?: string[];
};

const common: FeatureDefinition[] = [
  {
    id: 'auth-rbac',
    name: 'User roles & permissions',
    nameMm: 'အသုံးပြုသူ အခန်းကဏ္ဍနှင့် လုပ်ပိုင်ခွင့် (Admin/Staff/Manager)',
    desc: 'Role-based access control for admin, staff, and manager accounts.',
    baseCost: 280_000,
    category: 'essential',
    tags: ['core', 'auth', 'security'],
  },
  {
    id: 'auth-social',
    name: 'Social login (Google / Apple)',
    nameMm: 'Google/Apple အကောင့်ဖြင့် ဝင်ရောက်ခြင်း',
    desc: 'OAuth sign-in with Google and Apple.',
    baseCost: 170_000,
    category: 'essential',
    tags: ['auth'],
  },
  {
    id: 'admin-panel-dynamic',
    name: 'Admin dashboard',
    nameMm: 'ပင်မထိန်းချုပ်ခန်းနှင့် စနစ်ပြင်ဆင်မှုများ',
    desc: 'CRUD admin panel with system settings and configurations.',
    baseCost: 420_000,
    category: 'essential',
    tags: ['operations'],
  },
  {
    id: 'search-filter-advanced',
    name: 'Search & filters',
    nameMm: 'အဆင့်မြင့် ရှာဖွေခြင်းနှင့် စစ်ထုတ်ခြင်း',
    desc: 'Server-side search, pagination, and filtering for large datasets.',
    baseCost: 200_000,
    category: 'essential',
    tags: ['ux', 'performance'],
  },
  {
    id: 'file-upload-s3',
    name: 'File uploads (cloud)',
    nameMm: 'Cloud သို့ ဖိုင်တင်ခြင်း',
    desc: 'Secure uploads to S3, R2, or similar object storage.',
    baseCost: 120_000,
    category: 'essential',
    tags: ['core'],
  },
  {
    id: 'dashboard-analytics-charts',
    name: 'Charts & reports',
    nameMm: 'ဇယားများနှင့် အစီရင်ခံစာများ',
    desc: 'Visual analytics dashboards with exportable reports.',
    baseCost: 320_000,
    category: 'essential',
    tags: ['operations', 'analytics'],
  },
  {
    id: 'i18n',
    name: 'Multi-language',
    nameMm: 'ဘာသာစကားမျိုးစုံ (Unicode/English)',
    desc: 'Localization for Myanmar and English content.',
    baseCost: 140_000,
    category: 'essential',
    tags: ['ux'],
  },
  {
    id: 'data-export',
    name: 'Export to Excel / PDF',
    nameMm: 'Excel သို့မဟုတ် PDF ထုတ်ယူခြင်း',
    desc: 'Export lists and reports to spreadsheets or PDF.',
    baseCost: 140_000,
    category: 'essential',
    tags: ['operations'],
  },
  {
    id: 'audit-logs',
    name: 'Activity & audit logs',
    nameMm: 'လုပ်ဆောင်ချက် မှတ်တမ်းများ',
    desc: 'Track who changed records, payments, or inventory.',
    baseCost: 200_000,
    category: 'essential',
    tags: ['operations', 'security'],
  },
  {
    id: 'auth-email-password',
    name: 'Email & password login',
    nameMm: 'အီးမေးလ်နှင့် စကားဝှက်ဖြင့် ဝင်ရောက်ခြင်း',
    desc: 'Sign up, login, password reset, and verified email flows.',
    baseCost: 220_000,
    category: 'essential',
    tags: ['auth', 'core'],
  },
  {
    id: 'two-factor-auth',
    name: 'Two-factor authentication (2FA)',
    nameMm: 'နှစ်ဆင့်အတည်ပြုခြင်း',
    desc: 'OTP or authenticator app for sensitive accounts.',
    baseCost: 240_000,
    category: 'essential',
    tags: ['auth', 'security'],
  },
  {
    id: 'notifications-email',
    name: 'Email notifications',
    nameMm: 'အီးမေးလ်အသိပေးချက်များ',
    desc: 'Transactional emails for orders, alerts, and reminders.',
    baseCost: 160_000,
    category: 'essential',
    tags: ['engagement'],
  },
  {
    id: 'notifications-sms',
    name: 'SMS notifications',
    nameMm: 'SMS အသိပေးချက်များ',
    desc: 'Local SMS gateway for OTPs and alerts.',
    baseCost: 200_000,
    category: 'essential',
    tags: ['engagement', 'integration'],
  },
  {
    id: 'cms-content-pages',
    name: 'CMS content pages',
    nameMm: 'စာမျက်နှာများကို CMS ဖြင့် စံခြင်း',
    desc: 'Editable pages, blocks, or sections without redeploying.',
    baseCost: 280_000,
    category: 'essential',
    tags: ['content', 'cms'],
  },
  {
    id: 'webhooks-integrations',
    name: 'Webhooks & third-party hooks',
    nameMm: 'Webhooks နှင့် ပြင်ပစနစ်ချိတ်ဆက်မှု',
    desc: 'Outbound webhooks and integration endpoints for partners.',
    baseCost: 220_000,
    category: 'essential',
    tags: ['integration'],
  },
  {
    id: 'scheduled-tasks',
    name: 'Scheduled jobs & cron',
    nameMm: 'အချိန်ဇယားအလိုက် လုပ်ငန်းများ',
    desc: 'Background jobs for reports, clean-up, and recurring tasks.',
    baseCost: 190_000,
    category: 'essential',
    tags: ['operations'],
  },
];

const commerceAndInventory: FeatureDefinition[] = [
  {
    id: 'inventory-stock-tracking',
    name: 'Stock & low-stock alerts',
    nameMm: 'လက်ကျန်နှင့် ပစ္စည်းပြတ်သတိပေးချက်',
    desc: 'Real-time inventory with variants and batch tracking.',
    baseCost: 400_000,
    category: 'commerce',
    tags: ['inventory', 'pos'],
  },
  {
    id: 'inventory-multi-warehouse',
    name: 'Multi-branch / warehouses',
    nameMm: 'ဆိုင်ခွဲနှင့် ဂိုဒေါင်များ (Stock Transfer)',
    desc: 'Transfer stock between branches or warehouses.',
    baseCost: 500_000,
    category: 'commerce',
    tags: ['inventory', 'management'],
  },
  {
    id: 'pos-billing-invoice',
    name: 'POS billing & receipts',
    nameMm: 'အရောင်းပြေစာနှင့် Printer ချိတ်ဆက်မှု',
    desc: 'Point-of-sale billing with thermal receipt printing.',
    baseCost: 460_000,
    category: 'commerce',
    tags: ['pos', 'core'],
  },
  {
    id: 'supplier-purchase-orders',
    name: 'Suppliers & purchase orders',
    nameMm: 'ကုန်သွင်းသူနှင့် အဝယ်တော်လွှာ',
    desc: 'Manage suppliers and purchase order workflows.',
    baseCost: 300_000,
    category: 'commerce',
    tags: ['inventory', 'operations'],
  },
  {
    id: 'checkout-cart-promotions',
    name: 'Cart, checkout & promos',
    nameMm: 'လျှော့စျေးနှင့် ပရိုမိုရှင်း',
    desc: 'Shopping cart, checkout, and promotion rules.',
    baseCost: 260_000,
    category: 'commerce',
    tags: ['commerce', 'pos'],
  },
  {
    id: 'payments-manual',
    name: 'Manual payment (slip upload)',
    nameMm: 'ဘဏ်ဖြတ်ပိုင်း တင်ပြီး အတည်ပြုခြင်း',
    desc: 'Customers upload transfer slips; admin verifies payment.',
    baseCost: 120_000,
    category: 'commerce',
    tags: ['commerce'],
  },
  {
    id: 'product-catalog',
    name: 'Product catalog',
    nameMm: 'ကုန်ပစ္စည်းစာရင်း',
    desc: 'Categories, variants, pricing, and product detail pages.',
    baseCost: 320_000,
    category: 'commerce',
    tags: ['commerce', 'core'],
  },
  {
    id: 'product-reviews',
    name: 'Reviews & ratings',
    nameMm: 'သုံးသပ်ချက်နှင့် အဆင့်သတ်မှတ်ချက်',
    desc: 'Customer reviews with moderation and star ratings.',
    baseCost: 170_000,
    category: 'commerce',
    tags: ['commerce', 'engagement'],
  },
  {
    id: 'wishlist-favorites',
    name: 'Wishlist & favorites',
    nameMm: 'စိတ်ကြိုက် သိမ်းဆည်းခြင်း',
    desc: 'Save products or items for later across sessions.',
    baseCost: 130_000,
    category: 'commerce',
    tags: ['commerce', 'ux'],
  },
  {
    id: 'shipping-rates',
    name: 'Shipping & delivery zones',
    nameMm: 'ပို့ဆောင်ခနှင့် ဒေသအလိုက် ချိန်ညှိမှု',
    desc: 'Zone-based fees, pickup options, and delivery rules.',
    baseCost: 250_000,
    category: 'commerce',
    tags: ['commerce', 'logistics'],
  },
  {
    id: 'returns-refunds',
    name: 'Returns & refunds',
    nameMm: 'ပြန်အမ်းငွေနှင့် ကုန်ပြန်လည်မှု',
    desc: 'Return requests, refund workflow, and status tracking.',
    baseCost: 270_000,
    category: 'commerce',
    tags: ['commerce', 'operations'],
  },
  {
    id: 'loyalty-points',
    name: 'Loyalty & reward points',
    nameMm: 'အမှတ်စနစ်နှင့် ဆုလာဘ်များ',
    desc: 'Earn and redeem points on purchases or actions.',
    baseCost: 290_000,
    category: 'commerce',
    tags: ['commerce', 'engagement'],
  },
  {
    id: 'appointments-booking',
    name: 'Appointments & booking',
    nameMm: 'ရက်ချိန်းယူခြင်းနှင့် ဘുക്കုပ်ခြင်း',
    desc: 'Calendars, time slots, and booking confirmations.',
    baseCost: 360_000,
    category: 'commerce',
    tags: ['commerce', 'scheduling'],
  },
];

const edTechAndEducation: FeatureDefinition[] = [
  {
    id: 'edu-course-builder',
    name: 'Courses & lessons',
    nameMm: 'သင်ခန်းစာနှင့် သင်ရိုးညွှန်းတမ်း',
    desc: 'Course, module, and lesson content management.',
    baseCost: 360_000,
    category: 'education',
    tags: ['edtech', 'cms'],
  },
  {
    id: 'edu-video-streaming',
    name: 'Secure video streaming',
    nameMm: 'လုံခြုံသော ဗီဒီယိုကြည့်ရှုခြင်း',
    desc: 'Protected video delivery with anti-download measures.',
    baseCost: 320_000,
    category: 'education',
    tags: ['edtech', 'security'],
  },
  {
    id: 'edu-quiz-assignments',
    name: 'Quizzes & grading',
    nameMm: 'ဉာဏ်စမ်းနှင့် အမှတ်ပေးစနစ်',
    desc: 'Quizzes, exams, and automatic grading.',
    baseCost: 290_000,
    category: 'education',
    tags: ['edtech', 'engagement'],
  },
  {
    id: 'edu-student-progress',
    name: 'Progress & certificates',
    nameMm: 'တိုးတက်မှုနှင့် အောင်လက်မှတ်',
    desc: 'Student progress tracking and certificate generation.',
    baseCost: 260_000,
    category: 'education',
    tags: ['edtech', 'analytics'],
  },
  {
    id: 'edu-live-sessions',
    name: 'Live classes & webinars',
    nameMm: 'တိုက်ရိုက်သင်တန်းနှင့် ဝဘ်နာရ်',
    desc: 'Scheduled live sessions with attendance tracking.',
    baseCost: 380_000,
    category: 'education',
    tags: ['edtech', 'engagement'],
  },
  {
    id: 'edu-community-forums',
    name: 'Discussion forums',
    nameMm: 'ဆွေးနွေးခန်းနှင့် မေးခွန်းလက်ခံခြင်း',
    desc: 'Threads, replies, and moderation for learner communities.',
    baseCost: 240_000,
    category: 'education',
    tags: ['edtech', 'engagement'],
  },
  {
    id: 'edu-subscription-billing',
    name: 'Course subscriptions',
    nameMm: 'သင်တန်းအတွက် စာရင်းသွင်းငွေပေးချေမှု',
    desc: 'Recurring plans, trials, and access by subscription tier.',
    baseCost: 320_000,
    category: 'education',
    tags: ['edtech', 'commerce'],
  },
];

const webOnly: FeatureDefinition[] = [
  {
    id: 'seo-advanced',
    name: 'Advanced SEO',
    nameMm: 'အဆင့်မြင့် SEO (Next.js / Nuxt)',
    desc: 'SSR/SSG, meta tags, sitemaps, and indexing setup.',
    baseCost: 180_000,
    category: 'platform',
    tags: ['seo'],
  },
  {
    id: 'web-pwa',
    name: 'PWA (installable web app)',
    nameMm: 'ဖုန်းထဲ App ကဲ့သို့ ထည့်သွင်းအသုံးပြုခြင်း',
    desc: 'Progressive Web App install and offline shell.',
    baseCost: 210_000,
    category: 'platform',
    tags: ['performance', 'ux'],
  },
  {
    id: 'blog-news',
    name: 'Blog & news',
    nameMm: 'ဘလော့ဂ်နှင့် သတင်းများ',
    desc: 'Articles, categories, and publishing workflow.',
    baseCost: 220_000,
    category: 'platform',
    tags: ['content', 'seo'],
  },
  {
    id: 'contact-forms-advanced',
    name: 'Advanced contact & lead forms',
    nameMm: 'အဆင့်မြင့် ဆက်သွယ်ရေးနှင့် Lead ဖောင်များ',
    desc: 'Multi-step forms, validation, and lead routing.',
    baseCost: 140_000,
    category: 'platform',
    tags: ['core', 'marketing'],
  },
  {
    id: 'live-chat-widget',
    name: 'Live chat widget',
    nameMm: 'တိုက်ရိုက်စကားပြောချက်',
    desc: 'Embedded chat for sales or support on the website.',
    baseCost: 180_000,
    category: 'platform',
    tags: ['engagement', 'support'],
  },
  {
    id: 'email-newsletter',
    name: 'Newsletter signup',
    nameMm: 'သတင်းလွှာအတွက် စာရင်းသွင်းခြင်း',
    desc: 'Subscribe forms and list sync to email tools.',
    baseCost: 150_000,
    category: 'platform',
    tags: ['marketing', 'engagement'],
  },
];

const mobileOnly: FeatureDefinition[] = [
  {
    id: 'push-fcm',
    name: 'Push notifications',
    nameMm: 'အသိပေးချက် မက်ဆေ့ခ်ျများ',
    desc: 'Firebase push notifications with optional segments.',
    baseCost: 200_000,
    category: 'platform',
    tags: ['engagement'],
  },
  {
    id: 'mobile-offline-sync',
    name: 'Offline mode & sync',
    nameMm: 'အင်တာနက်မရှိချိန် အသုံးပြုနိုင်ခြင်း',
    desc: 'Local storage with sync when back online.',
    baseCost: 400_000,
    category: 'platform',
    tags: ['performance', 'core'],
  },
  {
    id: 'mobile-maps-routing',
    name: 'Maps & routing',
    nameMm: 'မြေပုံနှင့် တည်နေရာ',
    desc: 'Google Maps integration and location routing.',
    baseCost: 260_000,
    category: 'platform',
    tags: ['geolocation'],
  },
  {
    id: 'mobile-store-submission',
    name: 'App Store publishing help',
    nameMm: 'Store တင်ပေးခြင်း ပံ့ပိုးမှု',
    desc: 'Support for App Store and Play Store submission.',
    baseCost: 120_000,
    category: 'platform',
    tags: ['release'],
  },
  {
    id: 'payment-gateway-api',
    name: 'Payment gateway API',
    nameMm: 'KBZPay / Wave API ချိတ်ဆက်ခြင်း',
    desc: 'Automated KBZPay, Wave, or similar gateway integration.',
    baseCost: 360_000,
    category: 'platform',
    tags: ['commerce', 'integration'],
  },
  {
    id: 'biometric-auth',
    name: 'Biometric login',
    nameMm: 'လက်ဗွေနှင့် မျက်နှာဖြင့် ဝင်ရောက်ခြင်း',
    desc: 'Face ID, Touch ID, or fingerprint unlock.',
    baseCost: 240_000,
    category: 'platform',
    tags: ['auth', 'security'],
  },
  {
    id: 'deep-linking',
    name: 'Deep links & app links',
    nameMm: 'Deep link နှင့် App link များ',
    desc: 'Open specific screens from URLs, QR, or push taps.',
    baseCost: 170_000,
    category: 'platform',
    tags: ['engagement'],
  },
  {
    id: 'in-app-chat',
    name: 'In-app messaging',
    nameMm: 'အက်ပ်အတွင်း စကားပြောခြင်း',
    desc: 'User-to-user or user-to-support real-time chat.',
    baseCost: 320_000,
    category: 'platform',
    tags: ['engagement', 'support'],
  },
  {
    id: 'qr-scanner',
    name: 'QR & barcode scanner',
    nameMm: 'QR နှင့် ဘားကုဒ်ဖတ်ခြင်း',
    desc: 'Camera-based scan for products, tickets, or check-in.',
    baseCost: 190_000,
    category: 'platform',
    tags: ['core', 'pos'],
  },
  {
    id: 'referral-program',
    name: 'Referral & invite links',
    nameMm: 'မိတ်ဆွက်ခြင်းနှင့် ဖိတ်ခေါ်လင့်ခ်များ',
    desc: 'Share codes, invite rewards, and attribution tracking.',
    baseCost: 150_000,
    category: 'platform',
    tags: ['engagement', 'marketing'],
  },
  {
    id: 'app-rating-prompts',
    name: 'In-app review prompts',
    nameMm: 'အက်ပ်အကဲဖြတ်မှု တောင်းခံခြင်း',
    desc: 'Timed prompts to rate on App Store or Play Store.',
    baseCost: 90_000,
    category: 'platform',
    tags: ['release', 'engagement'],
  },
];

export const featuresCatalog: Record<ProductType, FeatureDefinition[]> = {
  web: [...common, ...commerceAndInventory, ...edTechAndEducation, ...webOnly],
  mobile: [
    ...common,
    ...commerceAndInventory,
    ...edTechAndEducation,
    ...mobileOnly,
  ],
};
